version: "3"

services:
  app:
    build: .
    restart: always
    depends_on:
      - database
    volumes:
      - ./:/app
      - gem_cache:/gems
    ports:
     - 3000:3000
    env_file:
     - .env
    environment: 
     - PATH=/gems/bin:$PATH
    command: /app/entrypoint.sh

  database:
    image: postgres:11.2-alpine
    restart: always
    env_file:
     - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh

volumes:
  gem_cache:
  db_data:
